services:

  app:
    image: ghcr.io/sectigo/ccadb-monitor:latest
    restart: unless-stopped
    container_name: ccadb_monitor
    ports:
      - "8080:80"
    environment:
      LOG_STACK: "slack"
      LOG_LEVEL: "debug"
      LOG_SLACK_WEBHOOK_URL: ""
      LOG_TEAMS_WEBHOOK_URL: ""
      DB_CONNECTION: "sqlite"
      DB_DATABASE: "db.sqlite"
      DB_HOST: ""
      DB_PORT: ""
      DB_USERNAME: ""
      DB_PASSWORD: ""
      CA_OWNER: ""


